basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: An API to demonstrate OpenAPI integration.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: My Awesome API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
